rvm: 1.8.7
before_install: rvm install rubygems 1.4.2; gem install rails -v=2.3.4  && cp config/database.yml.mysql config/database.yml && RAILS_ENV=cucumber rake gems:install && rake db:create:all db:schema:load && sudo apt-get install -y unzip

branches:
  only:
  - master
  - wip
