rvm: 1.8.7
before_install: rvm install rubygems 1.4.2; sudo apt-get install -y unzip
before_script:
  -"cp config/database.yml.mysql config/database.yml"
  -"bundle exec rake:db:create:all db:schema:load"

branches:
  only:
  - master
  - wip
