rvm: 1.9.3
before_install: rvm install rubygems 1.8.17; sudo apt-get install -y unzip
before_script:
  - "cp config/database.yml.mysql config/database.yml;"
  - "bundle exec rake db:create:all db:schema:load;"

services: 
  - memcached
branches:
  only:
  - master
  - wip
  - ruby_1.9.3
