rvm: 1.8.7
before_install: rvm install rubygems 1.8.17; sudo apt-get install -y unzip; sudo service memcached stop; sudo service memcached start
before_script:
  - "cp config/database.yml.mysql config/database.yml;"
  - "bundle exec rake db:create:all db:schema:load;"

branches:
  only:
  - master
  - wip
  - ruby_1.9.3
