language: ruby
gemfile: .travis.gemfile
rvm: 1.9.3

services:
  - memcached

#before_install: rvm install rubygems 1.8.17; sudo apt-get install -y unzip
before_install: sudo apt-get install -yqq unzip
before_script:
  - "cp config/database.yml.mysql config/database.yml;"
#  - "bundle exec rake db:schema:load"
# drop:all db:create:all db:schema:load;"
script: "bundle exec rake db:create db:schema:load default"
branches:
  only:
  - master
  - wip
