--- 
- :version: "> 2.0.0"
  :name: bluecloth
- :version: = 1.2.3
  :name: fastercsv
- :name: pdf-writer
- :version: ">= 1.0.0"
  :name: rack
- :name: system_timer
- :version: = 1.6.3
  :name: googlecharts
- :name: mysql
- :name: capistrano
- :name: capistrano-ext
- :version: 2.3.4
  :name: rails
  :version: 1.4.4
  :name: nokogiri
