# Primary domain application will be accessed as 
:domain: simspilot.org 
#wisims.org 

:default_url: https://www.simspilot.org

# Domain aliases for applaction. One common use of this is for asset hosts.
:domain_aliases:
  - "*.simspilot.org"
#  - assets2.sims.managedmachine.com

:ssl:
  :only: true
  :certificate_file: /home/rails/certs/2048/simspilot.org.crt
  :certificate_key_file: /home/rails/certs/2048/simspilot.org.key
  :certificate_chain_file: /home/rails/certs/2048/rapidssl-ca.crt


:network:
  :interfaces:
  - :name: eth0
    :desc: sims.widpi.managedmachine.com
    :address: 216.180.248.243
    :netmask: 255.255.255.0
    :network: 216.180.248.0
    :broadcast: 216.180.248.255
    :gateway: 216.180.248.1
  - :name: eth0:1
    :desc: simspilot.sims.widpi.managedmachine.com
    :address: 216.180.248.230
    :netmask: 255.255.255.0
    :network: 216.180.248.0
    :broadcast: 216.180.248.255
  - :name: eth0:2
    :desc: newdomain.sims.widpi.managedmachine.com
    :address: 216.180.248.244
    :netmask: 255.255.255.0
    :network: 216.180.248.0
    :broadcast: 216.180.248.255
  - :name: eth0:3
    :desc: "*.newdomain.sims.widpi.managedmachine.com"
    :address: 216.180.248.245
    :netmask: 255.255.255.0
    :network: 216.180.248.0
    :broadcast: 216.180.248.255
  - :name: eth1
    :desc: private sims.widpi
    :address: 10.0.4.243
    :netmask: 255.255.255.0
    :network: 10.0.4.0
    :broadcast: 10.0.4.255
  - :name: eth1:1
    :desc: private simspilot.sims.widpi
    :address: 10.0.4.230
    :netmask: 255.255.255.0
    :network: 10.0.4.0
    :broadcast: 10.0.4.255
  - :name: eth1:2
    :desc: private newdomain.sims.widpi
    :address: 10.0.4.244
    :netmask: 255.255.255.0
    :network: 10.0.4.0
    :broadcast: 10.0.4.255
  - :name: eth1:3
    :desc: private *.newdomain.sims.widpi
    :address: 10.0.4.245
    :netmask: 255.255.255.0
    :network: 10.0.4.0
    :broadcast: 10.0.4.255

